farm_back/farm_base/api/v1/urls.py
from __future__ import unicode_literals
from django.urls import path
from farm_base.views import detailsView, searchView, resultsView

from .views import FarmListCreateView, \
    FarmRetrieveUpdateDestroyView, OwnerListCreateView, \
    OwnerRetrieveUpdateDestroyView

urlpatterns = [
    path('farms', FarmListCreateView.as_view(),
         name="farms-list-create"),
    path('farms/<int:pk>', FarmRetrieveUpdateDestroyView.as_view(),
         name="farms-retrieve-update-destroy"),

    path('owners', OwnerListCreateView.as_view(),
         name="owners-list-create"),
    path('owners/<int:pk>',
         OwnerRetrieveUpdateDestroyView.as_view(),
         name="owners-retrieve-update-destroy"),
     path('search', searchView.as_view(), name='search'),
     path('results', resultsView.as_view(), name='results'),
     path('details/<farm_id>', detailsView.as_view(), name='details')
]

farm_back/farm_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Farm Project API",
        default_version='v1',
        description="A Test Project for new Agrosatelite Developers",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="webmaster@agrosatelite.com.br"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api/v1/', include(('farm_base.api.v1.urls',
                             'farm_base'),
                            namespace='farm_base')),
]

if settings.DEBUG:
    urlpatterns += [
        path('', RedirectView.as_view(url="/api/v1")),

        # swagger view
        re_path(r'^api/v1(?P<format>\.json|\.yaml)$',
                schema_view.without_ui(cache_timeout=0), name='schema-json'),
        re_path(r'^api/v1/$', schema_view.with_ui('swagger', cache_timeout=0),
                name='schema-swagger-ui'),
    ]

farm_back/farm_base/models/farm.py
from django.contrib.gis.db import models
from django.utils.translation import gettext as _
from farm_base.models import Owner


class Farm(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=255,
                            null=True, blank=False)

    geometry = models.GeometryField(verbose_name=_("Geometry"),
                                    null=True, blank=True)

    area = models.FloatField(verbose_name=_("Area"),
                             blank=True, null=True)

    centroid = models.PointField(verbose_name=_("Centroid"),
                                 blank=True, null=True)

    creation_date = models.DateTimeField(verbose_name=_("Creation date"),
                                         auto_now_add=True, editable=False)

    last_modification_date = models.DateTimeField(
        verbose_name=_("Last modification date"), auto_now=True)

    is_active = models.BooleanField(verbose_name=_("Is Active"), default=True)

    municipality = models.CharField(verbose_name=_("Municipality"), max_length=255,
                                    null=True, blank=False)

    state = models.CharField(verbose_name=_("State"), max_length=255,
                            null=True, blank=False)

    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, verbose_name=_("Owner"), null=True, blank=False)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['id']
        verbose_name = _('Farm')
        verbose_name_plural = _('Farms')

farm_back/farm_base/models/owner.py
from django.contrib.gis.db import models
from django.utils.translation import gettext as _


class Owner(models.Model):
    CPF = "CPF"
    CNPJ = "CNPJ"

    DOCUMENT_TYPE_CHOICES = (
        (CPF, "CPF"),
        (CNPJ, "CNPJ"),
    )

    name = models.CharField(verbose_name=_("Name"),
                            max_length=255)

    document = models.CharField(verbose_name=_("Document"),
                                max_length=255)

    document_type = models.CharField(verbose_name=_("Document type"),
                                     max_length=10,
                                     choices=DOCUMENT_TYPE_CHOICES)

    creation_date = models.DateTimeField(verbose_name=_("Creation date"),
                                         auto_now_add=True, editable=False)

    last_modification_date = models.DateTimeField(
        verbose_name=_("Last modification date"), auto_now=True)

    is_active = models.BooleanField(verbose_name=_("Is Active"), default=True)

    def __str__(self):
        return str(self.name)

    def get_class_name(self):
        return "owner"

    class Meta:
        unique_together = ['document', 'document_type']
        ordering = ['id']
        verbose_name = _('Owner')
        verbose_name_plural = _('Owners')

farm_back/farm_base/api/v1/views/farm.py
from rest_framework import generics

from farm_base.api.v1.serializers import FarmListSerializer, \
    FarmCreateSerializer, FarmDetailSerializer
from farm_base.models import Farm


class FarmListCreateView(generics.ListCreateAPIView):
    queryset = Farm.objects.filter(is_active=True)
    serializer_class = FarmListSerializer

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return FarmListSerializer
        else:
            return FarmCreateSerializer

    def perform_create(self, serializer):
        farm = serializer.save()
        area = float(farm.geometry.area)
        centroid = farm.geometry.centroid
        serializer.save(area=area, centroid=centroid)


class FarmRetrieveUpdateDestroyView(
    generics.RetrieveUpdateDestroyAPIView):
    queryset = Farm.objects.filter(is_active=True)
    serializer_class = FarmDetailSerializer

farm_back/farm_base/api/v1/views/owner.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import generics, filters

from farm_base.api.v1.filters import OwnerFilter
from farm_base.api.v1.serializers import OwnerListCreateSerializer, OwnerDetailSerializer
from farm_base.models import Owner


class OwnerListCreateView(generics.ListCreateAPIView):
    queryset = Owner.objects.filter(is_active=True)
    serializer_class = OwnerListCreateSerializer
    filter_backends = (DjangoFilterBackend,
                       filters.OrderingFilter)
    filterset_class = OwnerFilter
    search_fields = ['name', 'document']


class OwnerRetrieveUpdateDestroyView(
    generics.RetrieveUpdateDestroyAPIView):
    queryset = Owner.objects.filter(is_active=True)
    serializer_class = OwnerDetailSerializer

farm_back/farm_base/views.py
from django.views.generic import TemplateView, ListView
from django.shortcuts import render
from farm_base.api.v1.views import owner
from .models import Farm, Owner
from django.db.models import Q

class searchView(TemplateView):
    template_name = 'farm_base/search.html'

class resultsView(ListView):
    model = Farm
    template_name = 'farm_base/results.html'

    def get_queryset(self):
        q = self.request.GET.get("q")
        object_list = Farm.objects.filter(
            Q(owner__name__icontains=q) | Q(owner__document__icontains=q) | Q(name__icontains=q) | 
            Q(municipality__icontains=q) | Q(state__icontains=q) | Q(id__icontains=q)  
        )
        return object_list

class detailsView(TemplateView):
    template_name = 'farm_base/details.html'
    
    def get(self, request, farm_id):
        farm = Farm.objects.get(pk=farm_id)
        return render(request, self.template_name, {'farm': farm})
    

farm_back/farm_base/templates/farm_base/details.html
<html>
    <h1>Farm Details:</h1>
    <body>
        <table>
        <tr>
            <th>Farm name:</th>
            <th>{{farm.name}}</th>
        </tr>
        <tr>
            <th>Geometry:</th>
            <th>{{farm.geometry}}</th>
        </tr>
        <tr>
            <th>Area:</th>
            <th>{{farm.area}}</th>
        </tr>
        <tr>
            <th>Centroid:</th>
            <th>{{farm.centroid}}</th>
        </tr>
        <tr>
            <th>Creation Date:</th>
            <th>{{farm.creation_date}}</th>
        </tr>
        <tr>
            <th>Last modification date:</th>
            <th>{{farm.last_modification_date}}</th>
        </tr>
        <tr>
            <th>Is active:</th>
            <th>{{farm.is_active}}</th>
        </tr>
        <tr>
            <th>Municipality:</th>
            <th>{{farm.municipality}}</th>
        </tr>
        <tr>
            <th>State:</th>
            <th>{{farm.state}}</th>
        </tr>
        <tr>
            <th>Owner:</th>
            <th>{{farm.owner}}</th>
        </tr>
        </table>
    </body>
</html>

farm_back/farm_base/templates/farm_base/results.html
<html>
    <h1>Search Results</h1>
    <body>
        <table>
            <tr>
                <th>Farm Name</th>
                <th>Owner ID</th>
                <th>Centroid</th>
                <th>Area</th>
                <th>Municipality</th>
                <th>State</th>
            </tr>
            {% for farm in object_list %}
            <tr>
                <th><a href="{% url 'farm_base:details' farm.id %}" id="{{farm.id}}">{{farm.name}}</a></th>
                <th>{{farm.owner.id}}</th>
                <th>{{farm.centroid}}</th>
                <th>{{farm.area}}</th>
                <th>{{farm.municipality}}</th>
                <th>{{farm.state}}</th>
            </tr>
            {% endfor %}    
        </table>
    </body>
</html>

farm_back/farm_base/templates/farm_base/search.html
<html>
    <h1> Search for farms</h1>
    <form action="{% url 'farm_base:results' %}" method="get">
        <input name="q" type="text" placeholder="Search...">
    </form>
</html>